name: 'S3 Check'
description: 'Check if a file exists in an S3 bucket and set an output with true or false'
author: 'Danilo Tuler (tuler@pobox.com)'
branding:
  icon: file
  color: green
outputs:
  exists:
    description: \'true\' if file exists, \'false\' otherwise
runs:
  using: 'docker'
  image: 'Dockerfile'
